# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: .
author_email: arthurrabelopro@gmail.com
author_name: p2arthur
cloud_provider: netlify
preset_name: production
project_name: playground

