name: Release production_react

on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".vscode/**"
      - ".idea/**"
  
permissions:
  contents: read
  packages: read

jobs:
  validate:
    name: Validate production_react
    uses: ./.github/workflows/production-react-ci.yaml
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Netlify
    environment: frontend-prod
    
    needs:
      - validate
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install algokit
        run: pipx install algokit

      - name: Bootstrap dependencies
        run: algokit project bootstrap all --project-name 'production_react'
    