name: Check code base

on:
  workflow_call:
    inputs:
      run-build:
        required: false
        type: boolean
        default: true
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build
        if: ${{ inputs.run-build }}
        run: npm run build
