# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: <commit>
_src_path: <src>
author_email: None
author_name: None
cloud_provider: none
preset_name: production
project_name: production_react

